apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitops-app
  namespace: gitops
spec:
  replicas: 2
  selector:
    matchLabels:
      app: gitops-app
  template:
    metadata:
      labels:
        app: gitops-app
    spec:
      containers:
        - name: gitops-app
          image: luckytheracer/gitops-app:initial
          ports:
            - containerPort: 5000